# Generated by Django 6.0.7 on 2026-07-23 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_stockbatch_supplier'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitemline',
            name='warehouse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_lines', to='inventory.warehouse'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saleitemline',
            name='warehouse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_lines', to='inventory.warehouse'),
            preserve_default=False,
        ),
    ]
