# Generated by Django 6.0.7 on 2026-08-18 15:17

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('inventory', '0002_alter_stockbatch_options_alter_stockmovement_options_and_more'),
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'base_manager_name': 'all_objects', 'ordering': ['-date_paid', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='paymentallocation',
            options={'base_manager_name': 'all_objects'},
        ),
        migrations.AlterModelOptions(
            name='purchaseinvoice',
            options={'base_manager_name': 'all_objects', 'ordering': ['-date_received', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='purchaseitemline',
            options={'base_manager_name': 'all_objects'},
        ),
        migrations.AlterModelOptions(
            name='saleinvoice',
            options={'base_manager_name': 'all_objects', 'ordering': ['-date_dispatched', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='saleitemline',
            options={'base_manager_name': 'all_objects'},
        ),
        migrations.AlterModelOptions(
            name='salesreturn',
            options={'base_manager_name': 'all_objects', 'ordering': ['-date_returned', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='salesreturnitemline',
            options={'base_manager_name': 'all_objects'},
        ),
        migrations.AlterModelOptions(
            name='spoilageloss',
            options={'base_manager_name': 'all_objects', 'ordering': ['-date_reported', '-created_at']},
        ),
        migrations.AlterModelManagers(
            name='payment',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='paymentallocation',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='purchaseinvoice',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='purchaseitemline',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='saleinvoice',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='saleitemline',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='salesreturn',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='salesreturnitemline',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='spoilageloss',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SaleItemLineBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='accounts.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL)),
                ('sale_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batch_allocations', to='transactions.saleitemline')),
                ('stock_batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_allocations', to='inventory.stockbatch')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('sale_line', 'stock_batch'), name='uniq_saleline_batch')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
