# Generated by Django 6.0.7 on 2026-08-20 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_payment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='round_off',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='purchaseitemline',
            name='is_vat_applicable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='round_off',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='saleitemline',
            name='is_vat_applicable',
            field=models.BooleanField(default=True),
        ),
    ]
