# Generated by Django 6.0.7 on 2026-08-20 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_purchaseinvoice_round_off_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='round_off_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='round_off_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
