# Generated by Django 6.0.7 on 2026-07-25 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_purchaseinvoice_is_vat_inclusive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleinvoice',
            name='is_vat_inclusive',
            field=models.BooleanField(default=False, help_text='If true, VAT is extracted from the total. If false, VAT is added on top.'),
        ),
        migrations.AddField(
            model_name='saleinvoice',
            name='void_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
