# Generated by Django 6.0.7 on 2026-07-25 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='is_removed',
        ),
        migrations.AddField(
            model_name='item',
            name='delete_reason',
            field=models.TextField(blank=True, help_text='Reason for deleting/discontinuing the item', null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('deleted', 'Deleted')], default='active', max_length=10),
        ),
    ]
