# Generated by Django 6.0.7 on 2026-08-17 13:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('catalog', '0001_initial'),
        ('parties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='item',
            name='uniq_item_barcode_per_company',
        ),
        migrations.RemoveConstraint(
            model_name='itemprice',
            name='uniq_item_pricetier',
        ),
        migrations.RemoveConstraint(
            model_name='itemuom',
            name='uniq_itemuom_barcode_per_company',
        ),
        migrations.RemoveConstraint(
            model_name='unit',
            name='uniq_unit_name_per_company',
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('barcode', ''), _negated=True), models.Q(('is_deleted', True), _negated=True)), fields=('company', 'barcode'), name='uniq_item_barcode_per_company'),
        ),
        migrations.AddConstraint(
            model_name='itemprice',
            constraint=models.UniqueConstraint(fields=('item', 'price_tier', 'unit'), name='uniq_item_pricetier_unit'),
        ),
        migrations.AddConstraint(
            model_name='itemuom',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('barcode', ''), _negated=True), models.Q(('is_deleted', True), _negated=True)), fields=('company', 'barcode'), name='uniq_itemuom_barcode_per_company'),
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', True), _negated=True), fields=('company', 'name'), name='uniq_unit_name_per_company'),
        ),
    ]
