# Generated by Django 6.0.7 on 2026-08-01 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_item_default_supplier_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemprice',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
