# Generated by Django 6.0.7 on 2026-08-18 15:17

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_item_uniq_item_barcode_per_company_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'base_manager_name': 'all_objects', 'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'base_manager_name': 'all_objects', 'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='itemprice',
            options={'base_manager_name': 'all_objects'},
        ),
        migrations.AlterModelOptions(
            name='itemuom',
            options={'base_manager_name': 'all_objects'},
        ),
        migrations.AlterModelOptions(
            name='pricetier',
            options={'base_manager_name': 'all_objects', 'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'base_manager_name': 'all_objects', 'ordering': ['name']},
        ),
        migrations.AlterModelManagers(
            name='category',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='item',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='itemprice',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='itemuom',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='pricetier',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='unit',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
