# Generated by Django 6.0.7 on 2026-08-20 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_category_options_alter_item_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_vat_applicable',
            field=models.BooleanField(default=True, help_text='Uncheck for VAT-exempt goods (e.g. basic agri products)'),
        ),
    ]
