# Generated by Django 6.0.7 on 2026-08-01 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_itemprice_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricetier',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
