# Generated by Django 6.0.7 on 2026-08-06 16:49

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_pricetier_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemprice',
            name='entry_unit',
            field=models.ForeignKey(blank=True, help_text="Unit this tier's price is normally typed in. price itself always stays per base_unit.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.unit'),
        ),
        migrations.AlterField(
            model_name='itemuom',
            name='conversion_factor',
            field=models.DecimalField(decimal_places=2, help_text='e.g., If Base is Pcs and this is Carton, factor = 12', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
