# Generated by Django 6.0.7 on 2026-08-06 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_itemprice_entry_unit_alter_itemuom_conversion_factor'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='cost_entry_unit',
            field=models.ForeignKey(blank=True, help_text='Unit the cost is normally typed in (e.g. Carton). cost_price itself always stays per base_unit.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.unit'),
        ),
    ]
