# Generated by Django 6.0.7 on 2026-08-17 13:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('parties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='party',
            name='uniq_party_name_per_company',
        ),
        migrations.AddConstraint(
            model_name='party',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', True), _negated=True), fields=('company', 'name'), name='uniq_party_name_per_company'),
        ),
    ]
