# Generated by Django 6.0.7 on 2026-08-18 15:17

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0002_remove_party_uniq_party_name_per_company_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='party',
            options={'base_manager_name': 'all_objects', 'ordering': ['name']},
        ),
        migrations.AlterModelManagers(
            name='party',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
