# Generated by Django 5.0.6 on 2026-03-04 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_company_requestdemo_remove_sale_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone_num',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
