# Generated by Django 5.0.6 on 2026-03-04 16:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile_phone_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='PAN_ID',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='company',
            name='fiscal_year_start',
            field=models.CharField(default='shrawan', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=20, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
