# Generated by Django 5.0.6 on 2026-03-04 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_company_pan_id_company_fiscal_year_start_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='PAN_ID',
            new_name='tax_id',
        ),
    ]
