# Generated by Django 5.0.6 on 2026-03-05 13:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_usersession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersession',
            name='is_active',
        ),
        migrations.AddField(
            model_name='usersession',
            name='uuid',
            field=models.CharField(default=django.utils.timezone.now, max_length=40, unique=True),
            preserve_default=False,
        ),
    ]
