# Generated by Django 5.0.6 on 2026-03-05 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_usersession_is_active_usersession_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='fiscal_year_start',
        ),
        migrations.RemoveField(
            model_name='company',
            name='low_stock_threshold',
        ),
        migrations.AddField(
            model_name='company',
            name='contact_person',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
