# Generated by Django 5.0.6 on 2026-03-05 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_company_fiscal_year_start_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='contact_person',
        ),
    ]
