# Generated by Django 5.0.6 on 2026-03-06 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_item_party_payment_purchaseinvoice_purchaseitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='description',
        ),
    ]
