# Generated by Django 5.0.6 on 2026-03-06 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_party_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='supplier',
        ),
    ]
