# Generated by Django 5.0.6 on 2026-03-06 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_item_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='supplier',
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='supplier',
            field=models.ForeignKey(default=1, limit_choices_to={'party_type': 'supplier'}, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_invoices', to='core.party'),
            preserve_default=False,
        ),
    ]
